image:
  - Visual Studio 2017

platform:
  - x64

environment:
  C2_DEBUG: true
  nodejs_version: "10"

  matrix:
    - VSCODE_VERSION: "latest"
    - VSCODE_VERSION: "1.31.0"

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm install
  - npm audit --production
  - npm run compile
  - npm run webpack

build: off

test_script:
  - npm test

#on_failure:
#  - type .\out\tmp\workspaceFolder\FailedTestLogs\log_*.txt
