env:
  global:
    - C2_DEBUG=true
    # VSCE_PAT
    - secure: 'fYpe8D+dLl2mVkdwgE8X8j5XpGGp9A04oHDkrkZQpgHWXG7UCbrQwtCwIVVWEZUUls0JpGLP9A4/cmICAkHvzuVxvrF/43/T3qcW2an2+U/SzcYtN4wEqqgZNJl3MqSMeTHOVWHrlft/MQj6Y421GkX3sqkSi2Z2XVkPHolHuwu0ybfFzRlw1OVLVF4RjSsS77DDMFfcpUymMXgHV7MefSyznprpLxNk3M1MXKkelLd8KRorlnvX5VEGWrddmxKmOztTyCPHfs4pRUbP33yLj+qL3ASDtwQJUIZbHHqvFv6t3EOY4SjWRbeBjON2LfE07LPzI4q8224D9PlTIi6x1rK8oNRnceuzJ1AJ3JAWVeUqAvI415fuewaXUvmXUBQNLCvpt+ecLIqzkV3bbbO2+SLycVamSLIrh6v9BHiocD+Q25M8nhg1nHnpmV7gUBFhg3BzW7xApL6p8AosAl6DY73ePV4fHfuu7+8jvZusrSjCCfQztbFP2E5oJ/XAuj7WusUR4co28+vuLe0hubX3ZPXz3O8O0RsUSf8zRfyxaV/cwIe1iJIdc4m9Bz4iZR+AJQ5rFzfgsYjN8lTTra46SKsTmEjToCjGDR89FjO0w2xGBIH1xI7m7EZhDqgsBK7JFw6Vb2qNGHMTt20R+hh8YK3uaUxyjfcqbrRiADJSH9I='
    # GITHUB_API_KEY
    - secure: 'EKVdnikYRiL/f07epf3IPinU9ckWXHXxQrkam23ZviPf/L5brYu+BPOm4oWLjv8ekwDIDan7A+y4Nzck7h5JDXxLcHcbsZIU6Fgo3pNULBNFI22VNo3NpL5CKVGJ8dMpTyvMztLvpFpBwGpszRTLmN6BrW/C/if7qfEOqqT9CVKk226Q2N+GP7w/vTzSZYkkf+C0dyTyV+j20ZkWgSxKMv57LlW5bNoMfQ1lOagna98Jl3NupynR9+qk4t4o67fYAB+5PEE9erICmwcPuhrJ0za61G1S4tPkoLu7lwV+pvOA6LUlkbwCcC7EofJx6w/S1VcK+Ebs3zNTcDZtGGG8DaEFvov4r+cpRGuAlQxb14aL6v3kv8edYGvtQOaSlkw7tktCz1/m6NiKIyxluf+RYVyPws944z4WanpCKbH4z7wTA7EbXDMfRDG643hv05KeamueouqUfdWpiKPm7d1vA4grH0Bl538xQ3PAdxDFd4TJ0eGxaz74BMTzHCmHutdatbCJnwgSEGnDNDKwM6lCUHi76pjAy4lfClG+0Y2TxErK/0pXK2kPmeP0FHAGkkHgSffG99cn8ulzvtJ8dmRKvk2ne/NzEsWgKq9aadHAyy/iMWr3yncbbBm+xo22jaN8M2ZWf9x0Mqc0uDc6iqVLKGqVXt6KJu8jL25B9Bc1xck='
    # APPVEYOR_TOKEN
    - secure: 'WG8FVhmErK4sbqYMQLMoKvI4Q+/Huq2TA96YjQOjmSoqZ6JbmVAGcQZKoHYgDpuquFPETzwZdTy1ffRUrfDflQ+u8HaFuJh78a9lJVh5jW8cQx/n6m+UpY6SW+EN3Z/8TtT5dYY14g/R1AntAGjhM6E6mtABVDS0wwuW0JahIGCB4QK7YgtGg8ulWZlgXCo5MF4WXQWalVMMnEYbAuGLleXjjRxnXP4I70Sg1oFOH4zDtUpBuS5ihdpuWed8BrQtlP7fz1DSo71BEfbxUN1wlKvm2sMEa/FRjGbeAiWs6WqmZdrXGFpJPL10Ss6BtDKxTcbOfn27IynkI/Dyw6v5Q8HIzLcWnIysJrsCHlMqoSI4X6Ooj+l0FWeCndZX5uq2iQS7v4n+cbn94fTgD69bsKLHWORnrmuK2CDpCGtdnFqAe2KX7EaUyJCq0l7SPZA698Xf0JiG+vdXCoVL4/wWPlv1/pE1HXb9HB3JpjpLshg1ENVWq/ksZ6Hi3rFLNlvXkxy/36cGjlDBx7CIlpCeVjhqi4+G3JgJvhQ/kaimglMkA33Yo8bxQoVo8nQKEJ79KPKLvATVHkmVRXBAvIFQ6AqLhYHFlTZF1/XQ7SblE0PCyLNs6s8yq25lOns6EfEhGl6wLyNBLXT33CAY/6eJRlsuHVfKT0yBAYhhQ0dltMM='
    # DEPLOYER_MAIL
    - secure: 'MtSVNng2I8yGJSUjXwSq+AJu8BeccladOT/QRS2lXEnJ66Fk22H0vTZCwmSB+4vVx9pt8ybBLqueNkcpcCZ1VxNWyYlWVFYt/jFbXKAcZpry0vYXKVHvf3Mofb/c/PBI7wl6CNFpMzGgDES9D+nbZCWUpzwnO47wLNmC2zKpE0eAQkdOIEHe7I4J5bfgE2i4VeRjzh2V7ZduMGUVnH/WEv51eQF4JLa/n0SWFn3SF1YQ/BOnLDcSyrofbadtoEHQ6OPYfHNRtOLUC07S1HOgAqFiAW+iZ4xP4345sBLF5ZldAEASWJMop4hH3TVG3cBxzuv6ubIgzKrsvj4KnytscBGZYcRP+JiLdY8Kf2qeJhApFrOKvBAt+GSeJygXHSC08Zm3vqDlFqUQpoNfAuBiCOd4uqZbCZewAt+ckQCl+QUOVHiJDgulPaDgQfgwcpIF/C9BqsS6d0CIYTq8rTObOYcT8qp+oJIoDRgnOfxelDl12RNFeqyyxY3orhPPk72B5/793F0YUwooJX+JfsN1aFdG1BE36k8fDijhR2P6g4YbIVGswyz6ugvUGC4PdPBr+1AIWCAYnUXGwS9CtIo7Y2dKuR2+Vz3CmT5A/HZsd9xXJoPibEMLYuSpbd+J5522/uMO+t0hjt7NGkZmzTHiElw6kUUS2Dt9vhBwpHmqCDo='

language: node_js

compiler: clang

node_js: '10'

before_install:
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      #export CXX="g++-4.9" CC="gcc-4.9"
      export DISPLAY=':99.0'
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      sleep 3
    fi

install:
  - npm install
  - npm audit --production
  - npm run compile
  - npm run webpack # test dos not use it, but we are testing the webpack creation
  - ls -all out/dist

script:
  - npm test

after_failure:
  - cat ./out/tmp/workspaceFolder/FailedTestLogs/log_*.txt

jobs:
  include:
    - os: linux
      env: VSCODE_VERSION=latest
    - os: linux
      env: VSCODE_VERSION=1.31.0
    - os: linux
      env: VSCODE_VERSION=insiders
    - os: osx
      env: VSCODE_VERSION=latest
    - os: osx
      env: VSCODE_VERSION=1.31.0
    - os: osx
      env: VSCODE_VERSION=insiders
    - os: linux
      env: VSCODE_VERSION=latest
      stage: deploy
      script: npm run deploy
      # https://docs.travis-ci.com/user/conditions-v1
      if: branch = master && type = push && tag IS blank && repo = matepek/vscode-catch2-test-adapter
  allow_failures:
    - os: linux
      env: VSCODE_VERSION=insiders
    - os: osx
      env: VSCODE_VERSION=insiders
